### ISSUE TITLE
Составить интро

### ISSUE THREAD

**Issue by vladimirkachan** [vladimirkachan/homepage#6]
Составить интро (вступление), где в 2-4 предложениях описать, что заказчик делает, что нравится делать, что хочется делать лучше, что важно делать, и т.д.

**Comment by vova-kachan** [comment]
A group of FSB agents, assigned to work undercover in the goverment of the Russian Federation is successfully fulfilling its `task.
[https://youtu.be/6xkLdzrniYo](url)

**Comment by vova-kachan** [comment]
Внедрение в банду прошло успешно
[https://youtu.be/fTlP9L7srOg](url)

**Comment by vladimirkachan** [comment]
А-ха-ха-ха
